collections:
    book:
        output: true
    authors:
        output: true
        values : 
            layout: author

exclude:
    - bin
    - build
    - pdf
    - tex
    - contribs

gems:
  - jekyll-redirect-from
